# Generated by Django 2.2.3 on 2019-07-17 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetID', models.IntegerField(auto_created=True, unique=True)),
                ('target_title', models.CharField(max_length=80)),
                ('target_description', models.CharField(max_length=10000)),
                ('target_created_date', models.DateField(auto_now_add=True)),
                ('target_ownerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Target', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Target_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_number', models.IntegerField(auto_created=True)),
                ('target_assignmentID', models.IntegerField(auto_created=True, unique=True)),
                ('assignment_name', models.CharField(max_length=80)),
                ('assignment_description', models.CharField(max_length=10000)),
                ('assignment_due_date', models.DateField()),
                ('assignment_created_date', models.DateField(auto_now_add=True)),
                ('assignment_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_Assignment', to=settings.AUTH_USER_MODEL)),
                ('related_targetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.Target')),
            ],
        ),
    ]
