# Generated by Django 2.2.3 on 2019-07-19 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetID', models.IntegerField(auto_created=True, unique=True)),
                ('target_title', models.CharField(max_length=80)),
                ('target_description', models.CharField(max_length=10000)),
                ('target_created_date', models.DateField(auto_now_add=True)),
                ('target_ownerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Target', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Target_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_number', models.IntegerField(auto_created=True)),
                ('target_assignmentID', models.IntegerField(auto_created=True, unique=True)),
                ('assignment_name', models.CharField(max_length=80)),
                ('assignment_description', models.CharField(max_length=10000)),
                ('assignment_due_date', models.DateField()),
                ('assignment_created_date', models.DateField(auto_now_add=True)),
                ('assignment_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Target_Assignment', to=settings.AUTH_USER_MODEL)),
                ('related_targetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.Target')),
            ],
        ),
        migrations.CreateModel(
            name='rTarget_Assignments_Relationships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordID', models.IntegerField(auto_created=True, unique=True)),
                ('assignment_due_date', models.DateField(blank=True)),
                ('assignment_start_date', models.DateField(auto_now_add=True)),
                ('assignment_assigned_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rTarget_Assignments_Relationships', to=settings.AUTH_USER_MODEL)),
                ('related_target_assignmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.Target_Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='rTarget_Assigned_To',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordID', models.IntegerField(auto_created=True, unique=True)),
                ('target_completion_date', models.DateField(blank=True)),
                ('target_signup_date', models.DateField(auto_now_add=True)),
                ('assigned_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rTarget_Assignmed_To', to=settings.AUTH_USER_MODEL)),
                ('related_targetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.Target')),
            ],
        ),
        migrations.CreateModel(
            name='rAssignment_Activity_Relationships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordID', models.IntegerField(auto_created=True, unique=True)),
                ('activity_create_date', models.DateField(auto_now_add=True)),
                ('activity_type', models.CharField(max_length=20)),
                ('activity_description', models.CharField(max_length=10000)),
                ('activity_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rAssignment_Activity_Relationships', to=settings.AUTH_USER_MODEL)),
                ('rTarget_Assignment_RelationshipID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.rTarget_Assignments_Relationships')),
            ],
        ),
    ]
