# Generated by Django 2.2.3 on 2019-07-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_target_target_upated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='targetID',
        ),
        migrations.RemoveField(
            model_name='target_assignment',
            name='target_assignmentID',
        ),
    ]
