# Generated by Django 2.2.3 on 2019-07-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_auto_20190719_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='target_upated_date',
        ),
        migrations.AddField(
            model_name='target',
            name='targetID',
            field=models.IntegerField(auto_created=True, default=6, unique=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target_assignment',
            name='target_assignmentID',
            field=models.IntegerField(auto_created=True, default=1, unique=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rassignment_activity_relationships',
            name='activity_type',
            field=models.CharField(max_length=20),
        ),
    ]
