# Generated by Django 2.2.3 on 2019-07-20 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0004_auto_20190719_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='target_image',
            field=models.ImageField(default=' ', upload_to='uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='target',
            name='targetID',
            field=models.IntegerField(auto_created=True, unique=True),
        ),
        migrations.AlterField(
            model_name='target_assignment',
            name='related_targetID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='targets.Target'),
        ),
        migrations.AlterField(
            model_name='target_assignment',
            name='target_assignmentID',
            field=models.IntegerField(auto_created=True, unique=True),
        ),
    ]
